# Generated by Django 3.1 on 2020-09-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
